import type { FeedItem } from './types';
import { ITEM_COPY, type Lang } from './i18n';

export const FEED_ITEMS: FeedItem[] = [
  {
    id: 'urgent-client',
    icon: '🔴',
    source: 'URGENT',
    headline: 'Client needs an update now.',
    loud: true,
    signal: false,
    reveal: ['Already being handled.', 'No decision required from you.'],
    kind: 'mail',
    sender: 'Daniel Prasetyo',
    initials: 'DP',
    avatarColor: 'bg-rose-600',
    preview: 'RE: RE: FW: Client asking for status — can someone reply before the call?',
    minsAgo: 2,
    important: true,
  },
  {
    id: 'project-group',
    icon: '💬',
    source: 'PROJECT GROUP',
    headline: '17 unread messages.',
    loud: true,
    signal: false,
    reveal: ['14 conversation', '2 FYI', '1 emoji 👍', 'No decision required.'],
    kind: 'chat',
    sender: 'Site Team — Villa 12',
    initials: 'ST',
    avatarColor: 'bg-violet-600',
    preview: 'Rina: haha ok · Budi: 👍 · Rina: nanti aku kirim fotonya ya',
    minsAgo: 1,
    unread: 17,
  },
  {
    id: 'calendar',
    icon: '📅',
    source: 'CALENDAR',
    headline: 'Meeting starts in 10 minutes.',
    loud: true,
    signal: false,
    reveal: ['Agenda attached. You are optional.', 'No decision required right now.'],
    kind: 'calendar',
    sender: 'Weekly Coordination Sync',
    initials: 'WS',
    avatarColor: 'bg-sky-600',
    preview: '09:30 – 10:30 · Meeting Room 2 · 11 attendees · You are optional',
    minsAgo: 3,
    attachment: true,
  },
  {
    id: 'dm',
    icon: '👤',
    source: 'DIRECT MESSAGE',
    headline: '"Can you quickly check this?"',
    loud: true,
    signal: false,
    reveal: ['Not blocking anyone.', 'A "yes" can wait until lunch.', 'No decision required.'],
    kind: 'chat',
    sender: 'Maya Kusuma',
    initials: 'MK',
    avatarColor: 'bg-teal-600',
    preview: 'Can you quickly check this? 🙏 sorry to bother',
    minsAgo: 1,
    unread: 2,
  },
  {
    id: 'dashboard',
    icon: '📊',
    source: 'PROJECT DASHBOARD',
    headline: '92% — ON TRACK 🟢',
    loud: false,
    signal: false,
    reveal: ['FYI only.', 'No decision required.'],
    kind: 'report',
    sender: 'Project Dashboard (automated)',
    initials: 'PD',
    avatarColor: 'bg-emerald-700',
    preview: 'Weekly progress digest · 92% complete · status green · no action items',
    minsAgo: 26,
  },
  {
    id: 'permit',
    icon: '⚠️',
    source: 'PERMIT',
    headline: 'Expires in 12 days.',
    loud: false,
    signal: true,
    reveal: ['Renewal decision needed this week.'],
    consequence: 'A lapsed permit can stop site work entirely.',
    kind: 'mail',
    sender: 'Legal & Permits',
    initials: 'LP',
    avatarColor: 'bg-slate-600',
    preview: 'Building permit no. 447/IMB expires in 12 days. Renewal needs your sign-off.',
    minsAgo: 41,
    attachment: true,
  },
  {
    id: 'drawing',
    icon: '📐',
    source: 'DRAWING',
    headline: 'Latest revision awaiting confirmation.',
    loud: false,
    signal: true,
    reveal: ['Your confirmation releases fabrication.'],
    consequence: 'Waiting silently costs 3 days on the critical path.',
    kind: 'mail',
    sender: 'Ari Wibowo — Studio',
    initials: 'AW',
    avatarColor: 'bg-slate-600',
    preview: 'Rev C attached. We hold fabrication until you confirm. No rush from our side.',
    minsAgo: 68,
    attachment: true,
  },
  {
    id: 'variation',
    icon: '💰',
    source: 'VARIATION',
    headline: 'Potential +IDR 480M impact after Friday.',
    loud: false,
    signal: true,
    reveal: ['Decision required by Friday.'],
    consequence: 'Delay may create IDR 480M additional exposure.',
    kind: 'mail',
    sender: 'Quantity Surveyor',
    initials: 'QS',
    avatarColor: 'bg-slate-600',
    preview: 'VO-19 pricing locked until Friday. After that the contractor reprices at market.',
    minsAgo: 95,
    attachment: true,
  },
];

export const itemById = (id: string): FeedItem => {
  const item = FEED_ITEMS.find(i => i.id === id);
  if (!item) throw new Error(`Unknown feed item: ${id}`);
  return item;
};

/**
 * The same item, spoken in the participant's language.
 * English lives on the item itself; other languages come from ITEM_COPY.
 */
export const localized = (item: FeedItem, lang: Lang): FeedItem => {
  if (lang === 'en') return item;
  const copy = ITEM_COPY[lang]?.[item.id];
  return copy ? { ...item, ...copy } : item;
};
